version: "3"

output: prefixed

tasks:
  default:
    - task: prepare
    - task: check
    - task: test
    - task: integration

  clean:
    - rm -rf output

  tidy:
    - task: clean
    - go get -u ./...
    - go mod tidy

  prepare:
    - go get ./...

  check:
    - golangci-lint run --allow-parallel-runners

  test:
    - go test ./internal/...

  integration:
    - go test ./tests/...

  integrationUpdate:
    cmds:
      - go test ./tests/...
    env:
      UPDATE_SNAPSHOTS: true

  build:
    - task: check
    - task: test
    - go build -o output/nrl ./cmd/nrl/*

  run:
    - task: check
    - go run ./cmd/nrl/*
