name: CI

on:
  push:

jobs:
  test-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: "^1.14"

      - name: Lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.30
          working-directory: service

      - name: Test
        working-directory: service
        run: go test ./...
